### ISSUE TITLE
Add README.md for all problems

### ISSUE THREAD

**Issue by ameykhale** [funoctis/Project-Euler-Go#2]
Currently only 001 has a README.md file explaining the problem. Adding it is simple, just copy paste the Problem from the hackerrank page. Keep in mind the numbers and other similar special text cannot be copied and must be written manually.

**Comment by Boot-Error** [comment]
heya, I have solved some of Project Euler problem. I'm taking this issue up!

**Comment by ameykhale** [comment]
Merged! Feel free to add more Project Euler problem statements/solutions
